name: Bump Version on Merge

on:
  pull_request:
    types: [closed]
    branches: [dev]

jobs:
  bump-version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v4
        with:
          ref: dev
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Bump version and reset build trigger
        run: |
          npm version patch --no-git-tag-version
          # 修改 package.json 中的 buildTrigger
          npm pkg set config.buildTrigger=0

      - name: Commit version bump
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add package.json
          git commit -m "chore: bump version to $(node -p "require('./package.json').version")"

      - name: Push changes
        run: git push origin dev
